#!/usr/bin/env node
import { chmod, mkdir, readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join } from 'node:path';
import readline from 'node:readline/promises';
import { stdin as input, stdout as output } from 'node:process';

const DEFAULT_SERVER_URL = 'https://vera-cowork-server.ngrok.app';
const DEFAULT_AUTH_PATH = join(homedir(), '.letta-cowork', 'vera-auth.json');
const DEFAULT_ENV_PATH = join(homedir(), '.letta-cowork', 'vera-auth.env');

function parseArgs(argv) {
  const args = {
    serverUrl: process.env.VERA_SERVER_URL || DEFAULT_SERVER_URL,
    authPath: process.env.VERA_AUTH_FILE || DEFAULT_AUTH_PATH,
    envPath: process.env.VERA_AUTH_ENV_FILE || DEFAULT_ENV_PATH,
    printExports: false,
    refreshOnly: false,
  };

  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === '--server-url') args.serverUrl = argv[++i];
    else if (arg === '--auth-file') args.authPath = argv[++i];
    else if (arg === '--env-file') args.envPath = argv[++i];
    else if (arg === '--print-exports') args.printExports = true;
    else if (arg === '--refresh') args.refreshOnly = true;
    else if (arg === '-h' || arg === '--help') {
      printHelp();
      process.exit(0);
    }
  }
  args.serverUrl = args.serverUrl.replace(/\/+$/, '');
  return args;
}

function printHelp() {
  console.log(`Vera OTP login helper\n\nUsage:\n  node vera-login.mjs [--server-url URL]\n  node vera-login.mjs --refresh\n  node vera-login.mjs --print-exports\n\nEnvironment:\n  VERA_SERVER_URL        Vera server URL. Defaults to ${DEFAULT_SERVER_URL}\n  VERA_EMAIL             Optional email to avoid prompt.\n  VERA_AUTH_FILE         Token cache path. Defaults to ${DEFAULT_AUTH_PATH}\n  VERA_AUTH_ENV_FILE     Env file path. Defaults to ${DEFAULT_ENV_PATH}\n\nThis helper never prints token values unless --print-exports is passed.\nIt writes token cache and env files with chmod 600.`);
}

async function readJsonIfExists(path) {
  if (!existsSync(path)) return null;
  try {
    return JSON.parse(await readFile(path, 'utf8'));
  } catch {
    return null;
  }
}

async function requestJson(serverUrl, path, body) {
  const response = await fetch(`${serverUrl}${path}`, {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify(body),
  });

  const text = await response.text();
  let json;
  try {
    json = text ? JSON.parse(text) : {};
  } catch {
    json = { message: text };
  }

  if (!response.ok) {
    const message = Array.isArray(json.message) ? json.message.join('; ') : json.message;
    throw new Error(`${response.status} ${response.statusText}${message ? ` - ${message}` : ''}`);
  }
  return json;
}

function normalizeTokenResponse(serverUrl, json) {
  const expiresInSeconds = Number(json.expiresIn || json.expires_in || 0);
  const accessTokenExpiresAt = expiresInSeconds > 0
    ? new Date(Date.now() + expiresInSeconds * 1000).toISOString()
    : null;

  return {
    serverUrl,
    tokenType: json.tokenType || json.token_type || 'Bearer',
    accessToken: json.accessToken,
    refreshToken: json.refreshToken,
    expiresIn: expiresInSeconds || null,
    accessTokenExpiresAt,
    refreshTokenExpiresAt: json.refreshTokenExpiresAt || null,
    user: json.user || null,
    savedAt: new Date().toISOString(),
  };
}

function shellEscapeSingleQuoted(value) {
  return String(value).replace(/'/g, `'"'"'`);
}

function toEnvFile(auth) {
  const lines = [
    '# Generated by vera-login.mjs. Do not commit.',
    `export VERA_SERVER_URL='${shellEscapeSingleQuoted(auth.serverUrl)}'`,
    `export VERA_ACCESS_TOKEN='${shellEscapeSingleQuoted(auth.accessToken)}'`,
    `export VERA_REFRESH_TOKEN='${shellEscapeSingleQuoted(auth.refreshToken)}'`,
  ];
  if (auth.accessTokenExpiresAt) {
    lines.push(`export VERA_ACCESS_TOKEN_EXPIRES_AT='${shellEscapeSingleQuoted(auth.accessTokenExpiresAt)}'`);
  }
  if (auth.user?.id) lines.push(`export VERA_USER_ID='${shellEscapeSingleQuoted(auth.user.id)}'`);
  if (auth.user?.email) lines.push(`export VERA_USER_EMAIL='${shellEscapeSingleQuoted(auth.user.email)}'`);
  if (auth.user?.organizationId) lines.push(`export VERA_ORGANIZATION_ID='${shellEscapeSingleQuoted(auth.user.organizationId)}'`);
  return `${lines.join('\n')}\n`;
}

async function saveAuth(auth, authPath, envPath) {
  await mkdir(dirname(authPath), { recursive: true });
  await mkdir(dirname(envPath), { recursive: true });
  await writeFile(authPath, `${JSON.stringify(auth, null, 2)}\n`, { mode: 0o600 });
  await writeFile(envPath, toEnvFile(auth), { mode: 0o600 });
  await chmod(authPath, 0o600);
  await chmod(envPath, 0o600);
}

async function refresh(args) {
  const current = await readJsonIfExists(args.authPath);
  const refreshToken = process.env.VERA_REFRESH_TOKEN || current?.refreshToken;
  if (!refreshToken) throw new Error('No refresh token found. Run OTP login first.');
  const json = await requestJson(args.serverUrl, '/auth/refresh', { refreshToken });
  const auth = normalizeTokenResponse(args.serverUrl, {
    ...json,
    user: current?.user || json.user || null,
  });
  await saveAuth(auth, args.authPath, args.envPath);
  return auth;
}

async function otpLogin(args) {
  const rl = readline.createInterface({ input, output });
  try {
    const email = (process.env.VERA_EMAIL || await rl.question('Vera email: ')).trim();
    if (!email) throw new Error('Email is required.');

    await requestJson(args.serverUrl, '/auth/otp/request', { email });
    console.error(`OTP sent to ${email}.`);

    const otp = (await rl.question('OTP: ')).trim();
    if (!/^\d{6}$/.test(otp)) throw new Error('OTP must be exactly 6 digits.');

    const json = await requestJson(args.serverUrl, '/auth/otp/verify', { email, otp });
    const auth = normalizeTokenResponse(args.serverUrl, json);
    await saveAuth(auth, args.authPath, args.envPath);
    return auth;
  } finally {
    rl.close();
  }
}

function printSafeSummary(auth, args) {
  console.log(JSON.stringify({
    ok: true,
    serverUrl: auth.serverUrl,
    authFile: args.authPath,
    envFile: args.envPath,
    userEmail: auth.user?.email || process.env.VERA_EMAIL || null,
    userId: auth.user?.id || null,
    organizationId: auth.user?.organizationId || null,
    accessTokenExpiresAt: auth.accessTokenExpiresAt,
    hint: `Run: source ${args.envPath}`,
  }, null, 2));
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const auth = args.refreshOnly ? await refresh(args) : await otpLogin(args);

  if (args.printExports) {
    process.stdout.write(toEnvFile(auth));
    return;
  }

  printSafeSummary(auth, args);
}

main().catch((error) => {
  console.error(JSON.stringify({ ok: false, error: error.message }, null, 2));
  process.exit(1);
});
