import { afterEach, describe, expect, test } from "bun:test";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  coworkEnvFilePath,
  parseCoworkEnv,
  readCoworkAuth,
} from "./cowork-auth.js";

const cleanup = [];
afterEach(async () => {
  await Promise.all(
    cleanup.splice(0).map((path) => rm(path, { recursive: true, force: true })),
  );
});

async function testEnv(extra = {}) {
  const root = await mkdtemp(join(tmpdir(), "letta-vera-cowork-auth-"));
  cleanup.push(root);
  return {
    VERA_COWORK_ENV_PATH: join(root, "cowork.env"),
    ...extra,
  };
}

describe("Cowork authentication", () => {
  test("parses only supported assignments without executing shell syntax", () => {
    expect(
      parseCoworkEnv(`
# generated by Cowork
export COWORK_TOKEN='access-token'
VERA_COWORK_API_URL="https://vera.example.com"
UNRELATED=$(echo should-not-run)
`),
    ).toEqual({
      COWORK_TOKEN: "access-token",
      VERA_COWORK_API_URL: "https://vera.example.com",
    });
  });

  test("prefers the current cowork.env token over a stale process token", async () => {
    const env = await testEnv({ COWORK_TOKEN: "stale-process-token" });
    await writeFile(
      coworkEnvFilePath(env),
      "export COWORK_TOKEN=fresh-file-token\n",
      "utf8",
    );

    expect(await readCoworkAuth(env)).toEqual({
      accessToken: "fresh-file-token",
      serverUrl: null,
      source: "cowork.env",
    });
  });

  test("falls back to COWORK_TOKEN when the file is unavailable", async () => {
    const env = await testEnv({
      COWORK_TOKEN: "process-token",
      VERA_COWORK_API_URL: "https://vera.example.com",
    });

    expect(await readCoworkAuth(env)).toEqual({
      accessToken: "process-token",
      serverUrl: "https://vera.example.com",
      source: "COWORK_TOKEN",
    });
  });
});
